# Generated by Django 3.2.9 on 2021-11-25 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=600)),
                ('imagen', models.ImageField(upload_to='fotos')),
                ('meta', models.IntegerField(default=0)),
                ('frecuencia', models.CharField(default='', max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tags', models.ManyToManyField(related_name='newsletters', to='tags.Tag')),
                ('votos', models.ManyToManyField(related_name='newsletters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
