# Generated by Django 2.2.24 on 2021-11-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='imagen',
        ),
    ]
