# Generated by Django 3.2.9 on 2021-11-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_auto_20211125_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
