# Generated by Django 2.2.24 on 2021-11-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20211123_1333'),
        ('newsletters', '0003_auto_20211123_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='tags',
            field=models.ManyToManyField(related_name='newsletter', to='tags.Tag'),
        ),
    ]
