# Generated by Django 2.2.24 on 2021-11-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0004_newsletter_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='tags',
            field=models.ManyToManyField(related_name='newsletters', to='tags.Tag'),
        ),
    ]
