# Generated by Django 2.2.23 on 2021-11-23 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0005_auto_20211123_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='fotos'),
            preserve_default=False,
        ),
    ]
