# Generated by Django 2.2.23 on 2021-11-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0006_newsletter_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='frecuencia',
            field=models.CharField(default='', max_length=100),
        ),
    ]
