# Generated by Django 2.2.24 on 2021-11-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_usuario_sucribir_a'),
        ('newsletters', '0007_newsletter_frecuencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='meta',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='meta',
            field=models.ManyToManyField(related_name='newsletters', to='usuarios.Usuario'),
        ),
    ]
