# Generated by Django 2.2.24 on 2021-11-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0009_newsletter_votar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='votar',
        ),
    ]
