# Generated by Django 2.2.24 on 2021-11-24 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0010_remove_newsletter_votar'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='votar',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
