# Generated by Django 2.2.24 on 2021-11-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0011_newsletter_votar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='tags',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='votar',
            field=models.BooleanField(),
        ),
    ]
