# Generated by Django 2.2.24 on 2021-11-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20211123_1333'),
        ('newsletters', '0012_auto_20211124_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='tags',
            field=models.ManyToManyField(related_name='newsletters', to='tags.Tag'),
        ),
    ]
