# Generated by Django 3.2.9 on 2021-11-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_usuario_suscribir'),
        ('newsletters', '0013_newsletter_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='votar',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='meta',
            field=models.ManyToManyField(related_name='newsletters', to='usuarios.Usuario'),
        ),
    ]
