# Generated by Django 2.2.24 on 2021-11-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0005_auto_20211123_1348'),
        ('usuarios', '0003_auto_20211123_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sucribir_a',
            field=models.ManyToManyField(related_name='newsletters', to='newsletters.Newsletter'),
        ),
    ]
