# Generated by Django 2.2.24 on 2021-11-24 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_sucribir_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='sucribir_a',
        ),
    ]
