# Generated by Django 2.2.24 on 2021-11-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20211123_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
